"""Initial migration.

Revision ID: 082d4e6890cc
Revises: 
Create Date: 2023-10-12 12:40:57.500429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082d4e6890cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###
