name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: file permission
        run: chmod +x services/web/entrypoint.sh

      - name: Load environment variables
        run: source .env.dev

      - name: Build
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for services to start
        run: |
          while ! nc -z web 5000; do
            sleep 1
          done

      - name: Run Tests
        run: docker-compose -f docker-compose.yml exec web pytest
