name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: file permission
        run: chmod +x services/web/entrypoint.sh

      - name: Load environment variables
        run: source .env.dev

      - name: Build
        run: docker-compose -f docker-compose.yml up -d

      - name: Delay for 3 seconds before running tests
        run: sleep 3

      - name: Run backend Tests
        run: |
          docker-compose -f docker-compose.yml exec -T web python manage.py run_tests | tee tests_output.txt # Run tests

          if grep -q "FAILED tests" tests_output.txt; then
            echo "Pattern 'FAILED tests' found in test results. Exiting with code 1."
            exit 1
          else
            echo "Pattern 'FAILED tests' not found in test results."
          fi

      - name: Run frontend tests
        run: |
          docker exec vite-frontend npm run test | tee frontend_tests_output.txt # Run tests

          if grep -q "failed" frontend_tests_output.txt; then
            echo "Pattern 'FAIL' found in frontend test results. Exiting with code 1."
            exit 1
          else
            echo "Pattern 'FAIL' not found in frontend test results."
          fi
