name: 'Release to production'

on:
  release:
    types: [published]

jobs:
  release_frontend:
    name: 'Build backend'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Get current time'
        id: get_current_time
        run: echo "NOW=$(date --iso-8601=seconds)" >> $GITHUB_OUTPUT
